### ISSUE TITLE
Update Travis config

### ISSUE THREAD

**Issue by oubiwann** [lfe-deprecated/lfetool#106]
``` yaml
language: erlang
before_script: "make get-lfetool"
script: "make check"
notifications:
  #irc: "irc.freenode.org#YOUR-PROJECT-CHANNEL"
  recipients:
    #- YOU@YOUR.DOMAIN
otp_release:
  - 17.0
  - R16B03
  - R15B03
```
